### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by philipperemy** [YerevaNN/dmn-docker#1]
When running `docker run ...`, I'm having this error:

Setting up 4g of memory with -m didn't improve.

```
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: DimShuffle{x}(TensorConstant{1.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 1779, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 5993, in constant_folding
    no_recycling=[])
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 969, in make_thunk
    no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 872, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1591, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1502, in compile_cmodule
    preargs=preargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 2182, in compile_str
    p_out = output_subprocess_Popen(cmd)
  File "/usr/local/lib/python2.7/dist-packages/theano/misc/windows.py", line 76, in output_subprocess_Popen
    p = subprocess_Popen(command, **params)
  File "/usr/local/lib/python2.7/dist-packages/theano/misc/windows.py", line 37, in subprocess_Popen
    proc = subprocess.Popen(command, startupinfo=startupinfo, **params)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

Can you advice? Many thanks!

**Comment by philipperemy** [comment]
@mike1808 I'm running on a CPU on my laptop by the way. Thanks!

**Comment by philipperemy** [comment]
Okay finally I could make it work. I'm running on OSX and the problem was that by default, the OS allocates 1 CPU core and 2GB of memory.

http://stackoverflow.com/questions/32834082/how-to-increase-docker-machine-memory-mac

Running those commands solved the problem:

```
docker-machine stop
VBoxManage modifyvm default --cpus 2
VBoxManage modifyvm default --memory 4096
docker-machine start
```

**Comment by mike1808** [comment]
@philipperemy thanks for letting us know, I will write that requirement in the README.

**Comment by philipperemy** [comment]
@mike1808 Thanks a lot by the way. You guys are doing great work!
